### ISSUE TITLE
Error page for some searches

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/expert#4]
Reported by Dan Gledhill on 02/03/2015:

If you search for ‘Scombridae’ or ‘tunas & mackerels’ on fishmap, the following error message is generated in the family and species view (ie you can’t see all the pictures at once)
 
 ```
Grails Runtime Exception
Error Details
Error 500: Executing action [species] of controller [au.org.ala.tviewer.TaxonController] caused exception: Runtime error executing action
Servlet: grails
URI: /grails/taxon/species.dispatch
Exception Message: No such property: guid for class: org.codehaus.groovy.grails.web.json.JSONObject$Null 
Caused by: No such property: guid for class: org.codehaus.groovy.grails.web.json.JSONObject$Null 
Class: TaxonController 
At Line: [147] 
Code Snippet:
Stack Trace
groovy.lang.MissingPropertyException: No such property: guid for class: org.codehaus.groovy.grails.web.json.JSONObject$Null
        at au.org.ala.tviewer.BieService$_betterBulkLookup_closure5.doCall(BieService.groovy:89)
        at au.org.ala.tviewer.BieService.betterBulkLookup(BieService.groovy:88)
        at au.org.ala.tviewer.BieService.injectSpeciesMetadata(BieService.groovy:64)
        at au.org.ala.tviewer.TaxonController.species(TaxonController.groovy:147)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by nickdos** [comment]
Looks like a `tviewer` bug not `expert`. I'll move it.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/tviewer#1
